#!/usr/bin/env bash
set -euo pipefail

APP_DIR="/opt/vetka-backend-panel"
ENV_FILE="$APP_DIR/.env"
OVERRIDE_FILE="$APP_DIR/docker-compose.override.yml"
CADDY_FILE="$APP_DIR/Caddyfile"
REPO_URL="${REPO_URL:-https://github.com/Daniil-GR/vetka-backend-panel.git}"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/scripts/backup-common.sh"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/scripts/compose-runtime-common.sh"
PANEL_DOMAIN=""
SUBSCRIPTION_DOMAIN=""
ADMIN_USERNAME="admin"
PUBLIC_BASE_URL=""
PANEL_PUBLIC_BASE_URL=""
SUBSCRIPTION_PUBLIC_BASE_URL=""
ENABLE_HTTPS="yes"
EXPOSE_8080="no"
CONFIGURE_UFW="yes"
BACKUP_ENABLED="${BACKUP_ENABLED:-}"
BACKUP_DIR="${BACKUP_DIR:-}"
BACKUP_RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-}"
BACKUP_ON_CALENDAR="${BACKUP_ON_CALENDAR:-}"
BACKUP_BEFORE_UPDATE="${BACKUP_BEFORE_UPDATE:-}"

print_help() {
  cat <<'EOF'
Usage: install.sh [options]
  --panel-domain DOMAIN
  --subscription-domain DOMAIN
  --admin-username USERNAME
  --public-base-url URL
  --no-https
  --expose-8080
  --skip-ufw
EOF
}

random_secret() {
  openssl rand -hex 24
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

ensure_docker_service() {
  if ! command_exists systemctl; then
    echo "systemctl is required on this installer target." >&2
    exit 1
  fi
  systemctl enable --now docker
  if ! systemctl is-enabled docker >/dev/null 2>&1; then
    echo "Docker service is not enabled in systemd autostart." >&2
    exit 1
  fi
  if ! systemctl is-active docker >/dev/null 2>&1; then
    echo "Docker service is not running." >&2
    exit 1
  fi
  if ! docker info >/dev/null 2>&1; then
    echo "Docker daemon is not available." >&2
    exit 1
  fi
}

write_override_file() {
  if [[ "$EXPOSE_8080" == "yes" ]]; then
    cat >"$OVERRIDE_FILE" <<'EOF'
# Generated by Vetka Backend Panel installer
services:
  backend:
    ports:
      - "8080:8080"
EOF
  else
    if [[ -f "$OVERRIDE_FILE" ]]; then
      if grep -q "Generated by Vetka Backend Panel installer" "$OVERRIDE_FILE"; then
        rm -f "$OVERRIDE_FILE"
      else
        echo "Warning: existing docker-compose.override.yml was not changed because it is not installer-managed."
      fi
    fi
  fi
}

write_caddyfile() {
  if [[ "$ENABLE_HTTPS" != "yes" ]]; then
    return
  fi
  if [[ -f "$CADDY_FILE" ]] && ! grep -q "Generated by Vetka Backend Panel installer" "$CADDY_FILE"; then
    echo "Warning: existing Caddyfile was not changed because it is not installer-managed."
    return
  fi
  cat >"$CADDY_FILE" <<EOF
# Generated by Vetka Backend Panel installer
${PANEL_DOMAIN} {
  encode zstd gzip
  reverse_proxy backend:8080
}

${SUBSCRIPTION_DOMAIN} {
  encode zstd gzip

  handle /sub/* {
    reverse_proxy backend:8080
  }

  handle {
    respond "Not found" 404
  }
}
EOF
}

ask() {
  local prompt="$1"
  local default="$2"
  local answer
  read -r -p "$prompt [$default]: " answer || true
  if [[ -z "$answer" ]]; then
    answer="$default"
  fi
  printf '%s' "$answer"
}

confirm() {
  local prompt="$1"
  local default="$2"
  local answer
  read -r -p "$prompt [$default]: " answer || true
  if [[ -z "$answer" ]]; then
    answer="$default"
  fi
  [[ "$answer" =~ ^([Yy]|[Yy][Ee][Ss])$ ]]
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --panel-domain) PANEL_DOMAIN="${2:-}"; shift 2 ;;
    --subscription-domain) SUBSCRIPTION_DOMAIN="${2:-}"; shift 2 ;;
    --domain) SUBSCRIPTION_DOMAIN="${2:-}"; shift 2 ;;
    --admin-username) ADMIN_USERNAME="${2:-}"; shift 2 ;;
    --public-base-url) PUBLIC_BASE_URL="${2:-}"; shift 2 ;;
    --no-https) ENABLE_HTTPS="no"; shift ;;
    --expose-8080) EXPOSE_8080="yes"; shift ;;
    --skip-ufw) CONFIGURE_UFW="no"; shift ;;
    --help|-h) print_help; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

export DEBIAN_FRONTEND=noninteractive

if [[ -z "$PANEL_DOMAIN" ]]; then
  PANEL_DOMAIN="$(ask 'Panel domain (optional)' '')"
fi
if [[ -z "$SUBSCRIPTION_DOMAIN" ]]; then
  SUBSCRIPTION_DOMAIN="$(ask 'Subscription domain (optional)' "$PANEL_DOMAIN")"
fi
if [[ "$ENABLE_HTTPS" == "yes" ]]; then
  if ! confirm 'Enable HTTPS with Caddy?' 'Y'; then
    ENABLE_HTTPS="no"
  fi
fi
if [[ -z "$PUBLIC_BASE_URL" ]]; then
  if [[ -n "$SUBSCRIPTION_DOMAIN" ]]; then
    if [[ "$ENABLE_HTTPS" == "yes" ]]; then
      PUBLIC_BASE_URL="https://$SUBSCRIPTION_DOMAIN"
    else
      PUBLIC_BASE_URL="http://$SUBSCRIPTION_DOMAIN"
    fi
  else
    PUBLIC_BASE_URL="$(ask 'Legacy public base URL' 'http://localhost:8080')"
  fi
fi
if [[ -z "$PANEL_PUBLIC_BASE_URL" ]]; then
  if [[ -n "$PANEL_DOMAIN" ]]; then
    if [[ "$ENABLE_HTTPS" == "yes" ]]; then
      PANEL_PUBLIC_BASE_URL="https://$PANEL_DOMAIN"
    else
      PANEL_PUBLIC_BASE_URL="http://$PANEL_DOMAIN"
    fi
  else
    PANEL_PUBLIC_BASE_URL="$PUBLIC_BASE_URL"
  fi
fi
if [[ -z "$SUBSCRIPTION_PUBLIC_BASE_URL" ]]; then
  if [[ -n "$SUBSCRIPTION_DOMAIN" ]]; then
    if [[ "$ENABLE_HTTPS" == "yes" ]]; then
      SUBSCRIPTION_PUBLIC_BASE_URL="https://$SUBSCRIPTION_DOMAIN"
    else
      SUBSCRIPTION_PUBLIC_BASE_URL="http://$SUBSCRIPTION_DOMAIN"
    fi
  else
    SUBSCRIPTION_PUBLIC_BASE_URL="$PUBLIC_BASE_URL"
  fi
fi
if [[ "$EXPOSE_8080" == "no" ]]; then
  if confirm 'Expose direct 8080?' 'N'; then
    EXPOSE_8080="yes"
  fi
fi
if [[ "$CONFIGURE_UFW" == "yes" ]]; then
  if ! confirm 'Configure UFW?' 'Y'; then
    CONFIGURE_UFW="no"
  fi
fi
if [[ -z "$BACKUP_ENABLED" ]]; then
  if ! confirm 'Configure automatic backups?' 'Y'; then
    BACKUP_ENABLED="false"
  else
    BACKUP_ENABLED="true"
  fi
fi
if [[ "$BACKUP_ENABLED" == "true" ]]; then
  if [[ -z "$BACKUP_DIR" ]]; then
    BACKUP_DIR="$(ask 'Backup directory' '/var/backups/vetka-backend-panel')"
  fi
  if [[ -z "$BACKUP_RETENTION_DAYS" ]]; then
    BACKUP_RETENTION_DAYS="$(ask 'Retention days' '14')"
  fi
  if [[ -z "$BACKUP_ON_CALENDAR" ]]; then
    BACKUP_ON_CALENDAR="$(ask 'Backup schedule' '*-*-* 03:30:00 UTC')"
  fi
  if [[ -z "$BACKUP_BEFORE_UPDATE" ]]; then
    if ! confirm 'Backup before update?' 'Y'; then
      BACKUP_BEFORE_UPDATE="false"
    else
      BACKUP_BEFORE_UPDATE="true"
    fi
  fi
fi
if [[ -z "$PANEL_DOMAIN" ]]; then
  PANEL_DOMAIN="panel.localhost"
fi
if [[ -z "$SUBSCRIPTION_DOMAIN" ]]; then
  SUBSCRIPTION_DOMAIN="sub.localhost"
fi
BACKUP_DIR="${BACKUP_DIR:-/var/backups/vetka-backend-panel}"
BACKUP_RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-14}"
BACKUP_ON_CALENDAR="${BACKUP_ON_CALENDAR:-*-*-* 03:30:00 UTC}"
BACKUP_BEFORE_UPDATE="${BACKUP_BEFORE_UPDATE:-true}"

apt-get update
apt-get install -y ca-certificates curl git jq openssl docker.io docker-compose-v2 ufw
ensure_docker_service

mkdir -p "$APP_DIR"
chmod 755 "$APP_DIR"

if [[ -d "$APP_DIR/.git" ]]; then
  if confirm 'Repository exists. Update it now?' 'Y'; then
    git -C "$APP_DIR" fetch origin
    git -C "$APP_DIR" reset --hard origin/main
  fi
else
  git clone "$REPO_URL" "$APP_DIR"
fi
chmod 755 "$APP_DIR"/backup.sh "$APP_DIR"/restore.sh "$APP_DIR"/install.sh "$APP_DIR"/update.sh "$APP_DIR"/uninstall.sh 2>/dev/null || true
find "$APP_DIR/scripts" "$APP_DIR/tests" -type f -name '*.sh' -exec chmod 755 {} + 2>/dev/null || true

ADMIN_PASSWORD="$(random_secret)"
ADMIN_API_TOKEN="$(random_secret)"
POSTGRES_PASSWORD="$(random_secret)"

cat >"$ENV_FILE" <<EOF
APP_ENV=prod
HTTP_ADDR=:8080
PUBLIC_BASE_URL=$PUBLIC_BASE_URL
PANEL_PUBLIC_BASE_URL=$PANEL_PUBLIC_BASE_URL
SUBSCRIPTION_PUBLIC_BASE_URL=$SUBSCRIPTION_PUBLIC_BASE_URL
SUBSCRIPTION_PROFILE_TITLE=Ветка VPN
SUBSCRIPTION_UPDATE_INTERVAL_HOURS=12
APP_TIMEZONE=Europe/Moscow
EXPIRY_RECONCILE_ENABLED=true
EXPIRY_RECONCILE_INTERVAL=1m
DATABASE_URL=postgres://vetka:$POSTGRES_PASSWORD@postgres:5432/vetka_backend?sslmode=disable
ADMIN_USERNAME=$ADMIN_USERNAME
ADMIN_PASSWORD=$ADMIN_PASSWORD
ADMIN_API_TOKEN=$ADMIN_API_TOKEN
BACKEND_PUBLIC_IP=$(curl -fsSL https://api.ipify.org || echo 127.0.0.1)
NODE_AGENT_DEFAULT_PORT=2222
POSTGRES_USER=vetka
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=vetka_backend
PANEL_DOMAIN=$PANEL_DOMAIN
SUBSCRIPTION_DOMAIN=$SUBSCRIPTION_DOMAIN
ENABLE_HTTPS=$ENABLE_HTTPS
EXPOSE_8080=$EXPOSE_8080
BACKUP_ENABLED=$BACKUP_ENABLED
BACKUP_DIR=$BACKUP_DIR
BACKUP_RETENTION_DAYS=$BACKUP_RETENTION_DAYS
BACKUP_ON_CALENDAR=$BACKUP_ON_CALENDAR
BACKUP_BEFORE_UPDATE=$BACKUP_BEFORE_UPDATE
EOF
chmod 600 "$ENV_FILE"
write_override_file
write_caddyfile

if [[ "$ENABLE_HTTPS" == "yes" ]]; then
  (cd "$APP_DIR" && docker compose --profile https up -d --build)
else
  (cd "$APP_DIR" && docker compose up -d --build)
fi
if ! verify_compose_runtime; then
  echo "ERROR: Compose runtime verification failed." >&2
  exit 1
fi

if [[ "$CONFIGURE_UFW" == "yes" ]] && command_exists ufw; then
  ufw allow 22/tcp
  if [[ "$ENABLE_HTTPS" == "yes" ]]; then
    ufw allow 80/tcp
    ufw allow 443/tcp
  elif [[ "$EXPOSE_8080" == "yes" ]]; then
    ufw allow 8080/tcp
  fi
fi

show_compose_status
if ! verify_postgres_ready; then
  exit 1
fi
curl -fsSL "${PANEL_PUBLIC_BASE_URL%/}/login" >/dev/null 2>&1 || true

if [[ "$BACKUP_ENABLED" == "true" ]]; then
  BACKUP_DIR="$(vetka_assert_safe_backup_dir "$BACKUP_DIR")"
  vetka_ensure_dir_mode "$BACKUP_DIR" 700
  vetka_install_backup_units "$APP_DIR" "$BACKUP_DIR" "$BACKUP_ON_CALENDAR"
else
  vetka_remove_backup_units
fi

echo "Install completed."
echo "Panel URL: $PANEL_PUBLIC_BASE_URL"
echo "Subscription URL base: $SUBSCRIPTION_PUBLIC_BASE_URL"
echo "Admin username: $ADMIN_USERNAME"
echo "Admin password: $ADMIN_PASSWORD"
echo "Admin API token: $ADMIN_API_TOKEN"
echo "Database is private and is not published publicly."
echo "Next steps: open the panel, create a planned node or adopt an existing node, and keep the generated secrets in a safe place."
