#!/usr/bin/env bash
set -euo pipefail

APP_DIR="/opt/vetka-backend-panel"
ENV_FILE="$APP_DIR/.env"
OVERRIDE_FILE="$APP_DIR/docker-compose.override.yml"
REPO_URL="${REPO_URL:-https://github.com/Daniil-GR/vetka-backend-panel.git}"
DOMAIN=""
ADMIN_USERNAME="admin"
PUBLIC_BASE_URL=""
ENABLE_HTTPS="yes"
EXPOSE_8080="no"
CONFIGURE_UFW="yes"

print_help() {
  cat <<'EOF'
Usage: install.sh [options]
  --domain DOMAIN
  --admin-username USERNAME
  --public-base-url URL
  --no-https
  --expose-8080
  --skip-ufw
EOF
}

random_secret() {
  openssl rand -hex 24
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

write_override_file() {
  if [[ "$EXPOSE_8080" == "yes" ]]; then
    cat >"$OVERRIDE_FILE" <<'EOF'
# Generated by Vetka Backend Panel installer
services:
  backend:
    ports:
      - "8080:8080"
EOF
  else
    if [[ -f "$OVERRIDE_FILE" ]]; then
      if grep -q "Generated by Vetka Backend Panel installer" "$OVERRIDE_FILE"; then
        rm -f "$OVERRIDE_FILE"
      else
        echo "Warning: existing docker-compose.override.yml was not changed because it is not installer-managed."
      fi
    fi
  fi
}

ask() {
  local prompt="$1"
  local default="$2"
  local answer
  read -r -p "$prompt [$default]: " answer || true
  if [[ -z "$answer" ]]; then
    answer="$default"
  fi
  printf '%s' "$answer"
}

confirm() {
  local prompt="$1"
  local default="$2"
  local answer
  read -r -p "$prompt [$default]: " answer || true
  if [[ -z "$answer" ]]; then
    answer="$default"
  fi
  [[ "$answer" =~ ^([Yy]|[Yy][Ee][Ss])$ ]]
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain) DOMAIN="${2:-}"; shift 2 ;;
    --admin-username) ADMIN_USERNAME="${2:-}"; shift 2 ;;
    --public-base-url) PUBLIC_BASE_URL="${2:-}"; shift 2 ;;
    --no-https) ENABLE_HTTPS="no"; shift ;;
    --expose-8080) EXPOSE_8080="yes"; shift ;;
    --skip-ufw) CONFIGURE_UFW="no"; shift ;;
    --help|-h) print_help; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

export DEBIAN_FRONTEND=noninteractive

if [[ -z "$DOMAIN" ]]; then
  DOMAIN="$(ask 'Domain for panel/subscription (optional)' '')"
fi
if [[ "$ENABLE_HTTPS" == "yes" ]]; then
  if ! confirm 'Enable HTTPS with Caddy?' 'Y'; then
    ENABLE_HTTPS="no"
  fi
fi
if [[ -z "$PUBLIC_BASE_URL" ]]; then
  if [[ -n "$DOMAIN" ]]; then
    if [[ "$ENABLE_HTTPS" == "yes" ]]; then
      PUBLIC_BASE_URL="https://$DOMAIN"
    else
      PUBLIC_BASE_URL="http://$DOMAIN"
    fi
  else
    PUBLIC_BASE_URL="$(ask 'Public base URL' 'http://localhost:8080')"
  fi
fi
if [[ "$EXPOSE_8080" == "no" ]]; then
  if confirm 'Expose direct 8080?' 'N'; then
    EXPOSE_8080="yes"
  fi
fi
if [[ "$CONFIGURE_UFW" == "yes" ]]; then
  if ! confirm 'Configure UFW?' 'Y'; then
    CONFIGURE_UFW="no"
  fi
fi

apt-get update
apt-get install -y ca-certificates curl git jq openssl docker.io docker-compose-v2 ufw
systemctl enable --now docker

mkdir -p "$APP_DIR"
chmod 755 "$APP_DIR"

if [[ -d "$APP_DIR/.git" ]]; then
  if confirm 'Repository exists. Update it now?' 'Y'; then
    git -C "$APP_DIR" fetch origin
    git -C "$APP_DIR" reset --hard origin/main
  fi
else
  git clone "$REPO_URL" "$APP_DIR"
fi

ADMIN_PASSWORD="$(random_secret)"
ADMIN_API_TOKEN="$(random_secret)"
POSTGRES_PASSWORD="$(random_secret)"

cat >"$ENV_FILE" <<EOF
APP_ENV=prod
HTTP_ADDR=:8080
PUBLIC_BASE_URL=$PUBLIC_BASE_URL
DATABASE_URL=postgres://vetka:$POSTGRES_PASSWORD@postgres:5432/vetka_backend?sslmode=disable
ADMIN_USERNAME=$ADMIN_USERNAME
ADMIN_PASSWORD=$ADMIN_PASSWORD
ADMIN_API_TOKEN=$ADMIN_API_TOKEN
BACKEND_PUBLIC_IP=$(curl -fsSL https://api.ipify.org || echo 127.0.0.1)
NODE_AGENT_DEFAULT_PORT=2222
POSTGRES_USER=vetka
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=vetka_backend
CADDY_DOMAIN=${DOMAIN:-localhost}
ENABLE_HTTPS=$ENABLE_HTTPS
EXPOSE_8080=$EXPOSE_8080
EOF
chmod 600 "$ENV_FILE"
write_override_file

if [[ "$ENABLE_HTTPS" == "yes" ]]; then
  (cd "$APP_DIR" && docker compose --profile https up -d --build)
else
  (cd "$APP_DIR" && docker compose up -d --build)
fi

if [[ "$CONFIGURE_UFW" == "yes" ]] && command_exists ufw; then
  ufw allow 22/tcp
  if [[ "$ENABLE_HTTPS" == "yes" ]]; then
    ufw allow 80/tcp
    ufw allow 443/tcp
  elif [[ "$EXPOSE_8080" == "yes" ]]; then
    ufw allow 8080/tcp
  fi
fi

(cd "$APP_DIR" && docker compose ps)
(cd "$APP_DIR" && docker compose exec -T postgres pg_isready -U vetka -d vetka_backend)
curl -fsSL "${PUBLIC_BASE_URL%/}/login" >/dev/null 2>&1 || true

echo "Install completed."
echo "Panel URL: $PUBLIC_BASE_URL"
echo "Admin username: $ADMIN_USERNAME"
echo "Admin password: $ADMIN_PASSWORD"
echo "Admin API token: $ADMIN_API_TOKEN"
echo "Database is private and is not published publicly."
echo "Next steps: open the panel, create a planned node or adopt an existing node, and keep the generated secrets in a safe place."
